name: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    name: Build CI (Push)
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_BASEDIR: "${{ github.workspace }}"
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }} && success() && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup cmake
        run: |
          echo "ANDROID_HOME=${ANDROID_HOME}"
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"
          mkdir -p "$ANDROID_HOME/licenses/"
          echo > "$ANDROID_HOME/licenses/android-sdk-license"
          echo -n 24333f8a63b6825ea9c5514f83c2829b004d1fee > "$ANDROID_HOME/licenses/android-sdk-license"
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "cmake;3.22.1" --sdk_root=${ANDROID_SDK_ROOT}
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
      - name: Install ccache
        run: |
          sudo apt install -y ccache
          ccache -o max_size=1G
          ccache -o hash_dir=false
          ccache -o hard_link=true
          ccache -o compiler_check='%compiler% -dumpmachine; %compiler% -dumpversion'
          ccache -zp
      - name: Cache Native Build
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cache/ccache
            ~/.ccache
            app/build/.lto-cache
          key: native-cache-${{ github.sha }}
          restore-keys: native-cache-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.3.2

      - name: Build with Gradle
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties
          echo 'buildCache { local { removeUnusedEntriesAfterDays = 1 } }' >> settings.gradle.kts
          echo "/u3+7QAAAAIAAAABAAAAAQAHdGVzdGtleQAAAY82arztAAAFAjCCBP4wDgYKKwYBBAEqAhEBAQUABIIE6pc4DcgPa6y4mnO0wFLFx7eKOG44+S04duSDHWwUdONx77z/UTiencLrywugk+Yq5t7CUFUDOGcDF0BWVIn7CjDH5g58hqt7aNuzngwm1aTILnqFZuOJtswwcBWZX5eiVpT/rxljfWrXDZNxKPeUvrjme/F79ytDfwl8zPXszMyV9AUmzjRMlMvxcbe6RoThJlyoIZfl9qh273bwXMEg7KvyPGaxzVHx/NJvlXzhC4rBhQeCvB8MMqHEj/qMQHvaFNoNOE5iXEhDoyMBLj0ipJNQWWLjkvn2N4HZfvQxBCainZ+yI/efA21rTcTz54iKRFQncSNRE4VJEA45iqidgVZbrd9EYeh6qQXu+WJU4mGSbQ8IBVYDn3WzAgNreJzgjbexYFCADp7l/rGXzum+dzd+QPHu9PW1jaIAvFaPOKLI7OMK55KQF92Ib67mCr/jtbA1HVjCB6oUiG+AaWXMpV/Hb1CSJjxHW11vy9If6sydNMq9WjoihmYasmtOsPG6vAkL5fmo//4HMpKfIa5NFBJI/6YQ8Stxybl7WVrAeSw2z/xbSlDN4+vByY2ZyLGL9C9m0g1UdlYz064YJvv+Ybcn9ggjqcWM1Eo39IZgmIeiQ5NfdKTBCp2PYXcJp92THS3zVPH3E14ixoz4mXu5nwDysfE+PeVnMIFXuQvJZDPrbCKfF4AywIZ8vhp0j8ZROr1+roXdvgfFjgXXFz6mZ2dDIXlZhCpN7op0GQpufKXmsm8OPDUFLtEQgZX9cSJe7BzhR5getFAhM9sTHOjUPXUD/Z3VNJ0V2s+ZcqmVUGKYD6o5+GRrphidj5L7zB1XiNY2m2RG/X5HWokIin/QpO4DjAsF2CVouaiKbJKbNohFvYVBf8RzxnCapFsGDN2797v6Tr6oovuTg7Fx25FbUSlWKwQgUazoY8aVFyW/4Z4mIYUnu1gR8xmwWdYQnugNQEb6l3PBTotFf9XP+VTsIWT+c/7fYJFLlaXwkhaj2vs6EyvL9wI5dPUlRYm3pVdbZSb5VmkIJah1L1xd1A/owxWWjbFAurbumxjTZP9KZo1Mtt8RBsuxBQLXP0pAexAmgsFAnuNH1ofR4AfgoRXXIEoD3j6L+qCa1L0mP6sJ7KkD1uaYJJoFNsbiqi58cjmja4zLIlZEXzG1pO3S8qRXUwh//eV4A903hkW56aOi8MAAwK04Kx04QxI9t1qjWe1IrM64AZC6tUnCYRlQD56Tle4PUhd6gfVrvVhYSP7lnljgGVdyR9+hhyN6TPUzayvcGDLHnkjLZcl8d1XRbEFLdw0f1KhTMWn8kobuSMbFTI0LdW7m7EdOV6P4ni1QRMkZrYFscNPMKiRindwN/EjJUaJMp4MMshA5bSsXdsA5PE19KFHz4GPjjqK/jvbqbGQ4IQs2ZmTOiYM6GkYfXx3IcGr8m9QXi5S2GwjiVp99H8VnjBy0k+x65QwvVWcMGTpNYUtcIDs51tnUMI/hiN/Q9ZJ+JFv4LcCk/i40QV62qSHLhB6xybwMP9ibdmZxg9qmqNJBP0JOqziHx0/IJmJWyTAiTo+9w4Qno/nJWU6Jj1rLL11qQQEC0hcoVW8bPjga6PudliRhshzOIlT5WBCipMZva2fjLfGUsMDdP26J3JOZDbQntiju9Ct232wClL8XUgLJDPYmrGrqJzgAAAABAAVYLjUwOQAAApowggKWMIIBfqADAgECAgRTw6vAMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNVBAYTAkNOMB4XDTI0MDUwMTIzMDgzNVoXDTQ5MDQyNTIzMDgzNVowDTELMAkGA1UEBhMCQ04wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCfP30RTCPk4Z6ZdZJlArEWzc8fX69B+uiUZdgyq2cwx9YGlrAswoiKD2lu6VZ0TFECLcCFhnxxSo3s3zuEzp7ah4Ajx1RTYUjhHHEIvVaYlo1O36rW0ggz+G9C0tL/KtQ9//rUr0km18qs0MhCmv6W0y73xvoWG32jub4lPhr14Qop+4ijsPrjrqj5SHLZlV9i7++Ph+KgZ/mkGYouwNt1LlyNXAftHZ2Ph1iRAEiBNzkIWmSBGiX6PE2Um5JfdF91r08Upl99mPNu7x2ezmrlvCiF47PSUACmuaTN91fGWIm2PSq6bhYMnAdhnEpDiOjJY0bDKyEafydk8Fr1okPRAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAJm0q/bYYO5h04Wth//sbRLmJIv/viBJarl3yFHi2xfLWNLW9pWC26Ff5tjIAOKJI6tkizFJxZ21ve8hZ8x6K6zT85OLVznoWVHKCBodBQeXxZxk8duK45DEOhxeIOzx3zGvpxf+wTlUGNMsGczXCiDORo5/+U4zdsrvTjZ3Zmuih+PFIXJq4s3Ych33rj/ZYcV1gyDGlkLa4/mqTdU5rV31kweGZIUnH14BkpjakYjv9fID70tPIhOL2fsVO5gEeNsAy8QM87F6bgc4iP29HHzfvDlinaPdqLpIdvddyh/H3dz1gu/bq3bAwpXL5xTN0j5WeoI0UzWP1pHoofPmXfM3MovzhdYruA4pikMHoNkSVY8sxg==" | base64 -d > keystore.jks
          ./gradlew :app:synthesizeDistReleaseApksCI :app:extractReleaseNativeDebugMetadata
          ccache -s
          echo "APK_FILE_ARM32=$(find app/build/outputs/ci -name '*arm32.apk')" >> $GITHUB_ENV
          echo "APK_FILE_ARM64=$(find app/build/outputs/ci -name '*arm64.apk')" >> $GITHUB_ENV
          echo "APK_FILE_ARMALL=$(find app/build/outputs/ci -name '*armAll.apk')" >> $GITHUB_ENV
          echo "APK_FILE_UNIVERSAL=$(find app/build/outputs/ci -name '*universal.apk')" >> $GITHUB_ENV
          echo "SYMBOL_FILE=app/build/intermediates/native_debug_metadata/release/extractReleaseNativeDebugMetadata/out" >> $GITHUB_ENV
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASSWORD: "testkey"
          KEY_ALIAS: "testkey"
          KEY_PASSWORD: "testkey"

      - name: Show Artifacts SHA256
        run: |
          echo "### Build Success :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "|ABI|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
          arm32=($(sha256sum ${{ env.APK_FILE_ARM32 }}))
          echo "|arm32|$arm32" >> $GITHUB_STEP_SUMMARY
          arm64=($(sha256sum ${{ env.APK_FILE_ARM64 }}))
          echo "|arm64|$arm64" >> $GITHUB_STEP_SUMMARY
          armAll=($(sha256sum ${{ env.APK_FILE_ARMALL }}))
          echo "|armAll|$armAll" >> $GITHUB_STEP_SUMMARY
          universal=($(sha256sum ${{ env.APK_FILE_UNIVERSAL }}))
          echo "|universal|$universal" >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifacts(arm32)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.APK_FILE_ARM32 }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-arm32
      - name: Upload Artifacts(arm64)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.APK_FILE_ARM64 }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-arm64
      - name: Upload Artifacts(armAll)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.APK_FILE_ARMALL }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-armAll
      - name: Upload Artifacts(universal)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.APK_FILE_UNIVERSAL }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-universal
      - name: Upload Artifacts(symbol)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.SYMBOL_FILE }}
          name: QAuxiliary-release-${{ github.event.head_commit.id }}-symbol

  
